const assert=require('node:assert/strict');
const {prepare}=require('../chart-design.js');
const {wilson}=require('../chart-analysis.js');
const theme={text:'#111',muted:'#666',line:'#ddd',surface:'#fff'};
const ctx={width:360,theme,colors:['#a00','#077'],wilson};
const raw={foals:10,winners:5,graded_winners:1};
const rate={xAxis:{type:'category',data:['A','B']},yAxis:{type:'value',name:'胜马率'},series:[{name:'胜马率',type:'bar',data:[{value:50,raw},{value:0,raw:{foals:0,winners:0}}]}]};
const out=prepare('damAgePerformanceChart',rate,ctx).option;
assert.equal(out.xAxis[0].max,100);
assert.deepEqual(out.series[0].data[0].value,[50,0]);
assert.equal(out.series[0].data[0].raw,raw);
assert.equal(out.series[0].data[1].value[0],null);
assert.equal(out.series[1].data.length,1);
assert.deepEqual(out.series[1].data[0],[...wilson(5,10),0]);
const panels=prepare('sireCropWinnersChart',{xAxis:rate.xAxis,yAxis:[{type:'value',name:'匹'},{type:'value',name:'胜马率'}],series:[rate.series[0],{...rate.series[0],yAxisIndex:1}]},ctx).option;
assert.equal(panels.grid.length,2);assert.equal(panels.yAxis[1].max,100);assert.equal(panels.series[1].xAxisIndex,1);
const comp=prepare('breederCropChart',{xAxis:{type:'value'},yAxis:{type:'category',data:['farm']},series:[{type:'bar',stack:'c',data:[2]},{type:'bar',stack:'c',data:[3]}]},ctx).option;
assert.equal(comp.series.reduce((s,row)=>s+row.data[0].value,0),100);
assert.equal(comp.series[0].data[0].originalValue,2);
const profile=prepare('nickingSireChart',{series:[{data:[{raw:{label:'A',foals:10,winner_foal_rate:.5,graded_foal_rate:.1,avg_earnings_per_foal:200}}]}]}, {...ctx,baseline:{winner_foal_rate:.25,graded_foal_rate:.05,avg_earnings_per_foal:100}}).option;
assert.deepEqual(profile.series[0].data.map(d=>d.value[2]),[2,2,2]);
assert(rate.series[0].type==='bar');
const graded=prepare('bmsSexPerformanceChart',{...rate,yAxis:{type:'value',name:'重赏马率'},series:[{name:'牡马',type:'bar',data:[{value:10,raw}]}]},ctx).option;
assert.deepEqual(graded.series[1].data[0],[...wilson(1,10),0]);
assert.deepEqual(panels.series[1].data[0].value,['A',50]);
const sankey=prepare('clubBreederSankeyChart',{series:[{type:'sankey',label:{show:true,position:'inside'},data:[{name:'Farm'}]}]},ctx).option;
assert.equal(sankey.series[0].label.show,true);
const rank=prepare('sireLeadingAnnualRankChart',{xAxis:{type:'category'},yAxis:{type:'value',inverse:true},series:[{type:'line',data:[2,null,1]},{type:'scatter',data:[[2025,1]]}]},ctx);
assert.equal(rank.type,'trend');assert.equal(rank.option.series[0].connectNulls,false);assert.equal(rank.option.yAxis[0].inverse,true);

console.log('Verified chart transformations: samples, missingness, intervals, separate scales, shares and unweighted profiles.');
