const assert = require('node:assert/strict');
const {crops,tint,family,familyIdentity,ink} = require('../chart-colors.js');
assert.equal(Object.keys(crops).length,5);
assert.equal(new Set(Object.values(crops)).size,5);
assert.equal(crops[2018],'#742c46');
assert.equal(crops[2022],'#e4c568');
assert.equal(tint(crops[2018],0),crops[2018]);
assert.equal(tint(crops[2018],1),'#ffffff');
assert.equal(ink('#ffffff'),'#29242a');
assert.equal(ink('#000000'),'#ffffff');
assert.deepEqual(familyIdentity('F4-r'),{prefix:'F',number:4,branch:'r'});
assert.equal(family('F4-r'),family('4-r'));
assert.notEqual(family('A4'),family('F4'));
const rgb=c=>c.slice(1).match(/../g).map(v=>parseInt(v,16));
const distance=(a,b)=>Math.hypot(...rgb(a).map((v,i)=>v-rgb(b)[i]));
assert(distance(family('F4-a'),family('F4-b')) < 12);
assert(distance(family('F4-a'),family('F20-a')) > 70);
const shuffled=['F20-a','F4-r','F1-l','F4-a'];
for(const label of shuffled)assert.equal(family(label),family([...shuffled].reverse().find(v=>v===label)));
console.log('Verified stable cohort colours, family grouping, branch variation and heatmap contrast.');
